// RUN: circt-sim %s --max-time=100000000 --sim-stats | FileCheck %s

// Test APB-style clock generation and reset sequence.
// This mirrors the pattern generated by circt-verilog for APB AVIP.

// CHECK: [circt-sim] Found 3 LLHD processes
// CHECK: [circt-sim] Starting simulation
// CHECK: Reset deasserted
// CHECK: [circt-sim] Simulation completed at time 100000000 fs
// CHECK: Processes executed:
// CHECK: Delta cycles:
// CHECK: Signal updates:
// CHECK: [circt-sim] Simulation completed

hw.module @test() {
  %true = hw.constant true
  %false = hw.constant false
  %c0_i32 = hw.constant 0 : i32
  %c1_i32 = hw.constant 1 : i32
  %c-1_i32 = hw.constant -1 : i32
  %c10000000_i64 = hw.constant 10000000 : i64  // 10ns clock period (half)
  %c15000000_i64 = hw.constant 15000000 : i64  // 15ns reset delay
  %eps = llhd.constant_time <0ns, 0d, 1e>

  %fmt_reset = sim.fmt.literal "Reset deasserted\0A"

  // Clock signal (APB pclk)
  %pclk = llhd.sig %false : i1

  // Reset signal (APB preset_n, active low)
  %preset_n = llhd.sig %false : i1

  // Clock generation process
  llhd.process {
    llhd.drv %pclk, %false after %eps : i1
    cf.br ^bb1
  ^bb1:
    %delay = llhd.int_to_time %c10000000_i64
    llhd.wait delay %delay, ^bb2
  ^bb2:
    %clk_val = llhd.prb %pclk : i1
    %clk_inv = comb.xor %clk_val, %true : i1
    llhd.drv %pclk, %clk_inv after %eps : i1
    cf.br ^bb1
  }

  // Reset sequence process (assert then deassert after 1 clock)
  llhd.process {
    // Start with reset asserted (active low, so preset_n = 0)
    llhd.drv %preset_n, %false after %eps : i1
    %reset_delay = llhd.int_to_time %c15000000_i64
    llhd.wait delay %reset_delay, ^bb1
  ^bb1:
    // Deassert reset (preset_n = 1)
    llhd.drv %preset_n, %true after %eps : i1
    // Wait for posedge clock
    cf.br ^bb2(%c1_i32 : i32)
  ^bb2(%cnt: i32):
    %done = comb.icmp eq %cnt, %c0_i32 : i32
    cf.cond_br %done, ^bb_done, ^wait_edge
  ^wait_edge:
    %old_clk = llhd.prb %pclk : i1
    llhd.wait (%old_clk : i1), ^bb3
  ^bb3:
    %new_clk = llhd.prb %pclk : i1
    %old_inv = comb.xor %old_clk, %true : i1
    %posedge = comb.and %old_inv, %new_clk : i1
    cf.cond_br %posedge, ^dec_cnt, ^wait_edge
  ^dec_cnt:
    %new_cnt = comb.add %cnt, %c-1_i32 : i32
    cf.br ^bb2(%new_cnt : i32)
  ^bb_done:
    // Print message and halt
    sim.proc.print %fmt_reset
    llhd.halt
  }

  // Monitor process - detects reset deassertion
  llhd.process {
    cf.br ^bb1
  ^bb1:
    %rst_val = llhd.prb %preset_n : i1
    llhd.wait (%rst_val : i1), ^bb2
  ^bb2:
    %new_rst = llhd.prb %preset_n : i1
    // Check for rising edge on preset_n (reset deasserted)
    %old_was_low = comb.xor %rst_val, %true : i1
    %rising = comb.and %old_was_low, %new_rst : i1
    cf.cond_br %rising, ^halt, ^bb1
  ^halt:
    llhd.halt
  }

  hw.output
}
