//===- Coverage.td - Coverage dialect ---------------------------*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef CIRCT_DIALECT_COVERAGE_COVERAGE_TD
#define CIRCT_DIALECT_COVERAGE_COVERAGE_TD

include "circt/Dialect/Coverage/CoverageDialect.td"
include "circt/Dialect/Coverage/CoverageOps.td"

#endif // CIRCT_DIALECT_COVERAGE_COVERAGE_TD
